/cm/local/apps/slurm/var/spool/job10409/slurm_script: line 10: apt-get: command not found
ERROR: Unable to locate a modulefile for 'apps/ffmpeg/4.1/gcc-4.9.4'
ERROR: Unable to locate a modulefile for 'apps/ffmpeg/4.3.2/gcc-8.2-cmake-3.17.1'
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: transformers in ./.local/lib/python3.10/site-packages (4.27.3)
Requirement already satisfied: datasets in ./.local/lib/python3.10/site-packages (2.10.1)
Requirement already satisfied: evaluate in ./.local/lib/python3.10/site-packages (0.4.0)
Requirement already satisfied: librosa in ./.local/lib/python3.10/site-packages (0.10.0.post2)
Requirement already satisfied: torchmetrics in ./.local/lib/python3.10/site-packages (0.11.4)
Requirement already satisfied: opensmile in ./.local/lib/python3.10/site-packages (2.4.2)
Requirement already satisfied: regex!=2019.12.17 in ./.local/lib/python3.10/site-packages (from transformers) (2023.3.23)
Requirement already satisfied: filelock in ./.local/lib/python3.10/site-packages (from transformers) (3.10.2)
Requirement already satisfied: requests in /app/python/3.10.5/lib/python3.10/site-packages (from transformers) (2.28.1)
Requirement already satisfied: packaging>=20.0 in /app/python/3.10.5/lib/python3.10/site-packages (from transformers) (21.3)
Requirement already satisfied: huggingface-hub<1.0,>=0.11.0 in ./.local/lib/python3.10/site-packages (from transformers) (0.13.3)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in ./.local/lib/python3.10/site-packages (from transformers) (0.13.2)
Requirement already satisfied: numpy>=1.17 in /app/python/3.10.5/lib/python3.10/site-packages (from transformers) (1.22.4)
Requirement already satisfied: pyyaml>=5.1 in /app/python/3.10.5/lib/python3.10/site-packages (from transformers) (6.0)
Requirement already satisfied: tqdm>=4.27 in ./.local/lib/python3.10/site-packages (from transformers) (4.65.0)
Requirement already satisfied: pandas in /app/python/3.10.5/lib/python3.10/site-packages (from datasets) (1.4.3)
Requirement already satisfied: xxhash in ./.local/lib/python3.10/site-packages (from datasets) (3.2.0)
Requirement already satisfied: responses<0.19 in ./.local/lib/python3.10/site-packages (from datasets) (0.18.0)
Requirement already satisfied: dill<0.3.7,>=0.3.0 in ./.local/lib/python3.10/site-packages (from datasets) (0.3.6)
Requirement already satisfied: aiohttp in /app/python/3.10.5/lib/python3.10/site-packages (from datasets) (3.8.3)
Requirement already satisfied: fsspec[http]>=2021.11.1 in /app/python/3.10.5/lib/python3.10/site-packages (from datasets) (2022.5.0)
Requirement already satisfied: multiprocess in ./.local/lib/python3.10/site-packages (from datasets) (0.70.14)
Requirement already satisfied: pyarrow>=6.0.0 in /app/python/3.10.5/lib/python3.10/site-packages (from datasets) (8.0.0)
Requirement already satisfied: audioread>=2.1.9 in ./.local/lib/python3.10/site-packages (from librosa) (3.0.0)
Requirement already satisfied: scikit-learn>=0.20.0 in /app/python/3.10.5/lib/python3.10/site-packages (from librosa) (1.1.1)
Requirement already satisfied: numba>=0.51.0 in /app/python/3.10.5/lib/python3.10/site-packages (from librosa) (0.55.2)
Requirement already satisfied: soundfile>=0.12.1 in ./.local/lib/python3.10/site-packages (from librosa) (0.12.1)
Requirement already satisfied: soxr>=0.3.2 in ./.local/lib/python3.10/site-packages (from librosa) (0.3.4)
Requirement already satisfied: decorator>=4.3.0 in /app/python/3.10.5/lib/python3.10/site-packages (from librosa) (5.1.1)
Requirement already satisfied: scipy>=1.2.0 in /app/python/3.10.5/lib/python3.10/site-packages (from librosa) (1.8.1)
Requirement already satisfied: pooch<1.7,>=1.0 in ./.local/lib/python3.10/site-packages (from librosa) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.1 in /app/python/3.10.5/lib/python3.10/site-packages (from librosa) (4.3.0)
Requirement already satisfied: msgpack>=1.0 in /app/python/3.10.5/lib/python3.10/site-packages (from librosa) (1.0.4)
Requirement already satisfied: lazy-loader>=0.1 in ./.local/lib/python3.10/site-packages (from librosa) (0.2)
Requirement already satisfied: joblib>=0.14 in /app/python/3.10.5/lib/python3.10/site-packages (from librosa) (1.1.0)
Requirement already satisfied: torch>=1.8.1 in /app/python/3.10.5/lib/python3.10/site-packages (from torchmetrics) (1.12.0+cu116)
Requirement already satisfied: audobject>=0.6.1 in ./.local/lib/python3.10/site-packages (from opensmile) (0.7.9)
Requirement already satisfied: audinterface>=0.7.0 in ./.local/lib/python3.10/site-packages (from opensmile) (1.0.1)
Requirement already satisfied: audresample<2.0.0,>=1.1.0 in ./.local/lib/python3.10/site-packages (from audinterface>=0.7.0->opensmile) (1.2.1)
Requirement already satisfied: audmath>=1.2.1 in ./.local/lib/python3.10/site-packages (from audinterface>=0.7.0->opensmile) (1.2.1)
Requirement already satisfied: audformat<2.0.0,>=0.15.3 in ./.local/lib/python3.10/site-packages (from audinterface>=0.7.0->opensmile) (0.16.1)
Requirement already satisfied: oyaml in ./.local/lib/python3.10/site-packages (from audobject>=0.6.1->opensmile) (1.0)
Requirement already satisfied: audeer>=1.18.0 in ./.local/lib/python3.10/site-packages (from audobject>=0.6.1->opensmile) (1.19.0)
Requirement already satisfied: importlib-metadata>=4.8.0 in ./.local/lib/python3.10/site-packages (from audobject>=0.6.1->opensmile) (6.4.1)
Requirement already satisfied: setuptools in /app/python/3.10.5/lib/python3.10/site-packages (from numba>=0.51.0->librosa) (58.1.0)
Requirement already satisfied: llvmlite<0.39,>=0.38.0rc1 in /app/python/3.10.5/lib/python3.10/site-packages (from numba>=0.51.0->librosa) (0.38.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /app/python/3.10.5/lib/python3.10/site-packages (from packaging>=20.0->transformers) (3.0.9)
Requirement already satisfied: appdirs>=1.3.0 in /app/python/3.10.5/lib/python3.10/site-packages (from pooch<1.7,>=1.0->librosa) (1.4.4)
Requirement already satisfied: certifi>=2017.4.17 in /app/python/3.10.5/lib/python3.10/site-packages (from requests->transformers) (2022.6.15)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /app/python/3.10.5/lib/python3.10/site-packages (from requests->transformers) (1.26.9)
Requirement already satisfied: charset-normalizer<3,>=2 in /app/python/3.10.5/lib/python3.10/site-packages (from requests->transformers) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in /app/python/3.10.5/lib/python3.10/site-packages (from requests->transformers) (3.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in /app/python/3.10.5/lib/python3.10/site-packages (from scikit-learn>=0.20.0->librosa) (3.1.0)
Requirement already satisfied: cffi>=1.0 in /app/python/3.10.5/lib/python3.10/site-packages (from soundfile>=0.12.1->librosa) (1.15.1)
Requirement already satisfied: frozenlist>=1.1.1 in /app/python/3.10.5/lib/python3.10/site-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /app/python/3.10.5/lib/python3.10/site-packages (from aiohttp->datasets) (22.1.0)
Requirement already satisfied: aiosignal>=1.1.2 in /app/python/3.10.5/lib/python3.10/site-packages (from aiohttp->datasets) (1.2.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /app/python/3.10.5/lib/python3.10/site-packages (from aiohttp->datasets) (1.8.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /app/python/3.10.5/lib/python3.10/site-packages (from aiohttp->datasets) (6.0.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /app/python/3.10.5/lib/python3.10/site-packages (from aiohttp->datasets) (4.0.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /app/python/3.10.5/lib/python3.10/site-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /app/python/3.10.5/lib/python3.10/site-packages (from pandas->datasets) (2022.1)
Requirement already satisfied: iso-639 in ./.local/lib/python3.10/site-packages (from audformat<2.0.0,>=0.15.3->audinterface>=0.7.0->opensmile) (0.4.5)
Requirement already satisfied: iso3166 in ./.local/lib/python3.10/site-packages (from audformat<2.0.0,>=0.15.3->audinterface>=0.7.0->opensmile) (2.1.1)
Requirement already satisfied: audiofile>=0.4.0 in ./.local/lib/python3.10/site-packages (from audformat<2.0.0,>=0.15.3->audinterface>=0.7.0->opensmile) (1.2.1)
Requirement already satisfied: pycparser in /app/python/3.10.5/lib/python3.10/site-packages (from cffi>=1.0->soundfile>=0.12.1->librosa) (2.21)
Requirement already satisfied: zipp>=0.5 in ./.local/lib/python3.10/site-packages (from importlib-metadata>=4.8.0->audobject>=0.6.1->opensmile) (3.15.0)
Requirement already satisfied: six>=1.5 in /app/python/3.10.5/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas->datasets) (1.16.0)
2023-04-17 19:34:51.248001: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Some weights of the model checkpoint at MIT/ast-finetuned-audioset-10-10-0.4593 were not used when initializing ASTModel: ['classifier.layernorm.bias', 'classifier.dense.bias', 'classifier.dense.weight', 'classifier.layernorm.weight']
- This IS expected if you are initializing ASTModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing ASTModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Downloading and preparing dataset dataloadermultimodal/daic_woz to /ibm/gpfs/home/snag0027/speech-depression/cluster/cache_daic_woz/dataloadermultimodal/daic_woz-data_dir=./0.0.1/84c500e2c0e4323e8e54e8719d7409d1eaa628c9b4244aa8b08663953138d9a0...
Generating train split: 0 examples [00:00, ? examples/s]Generating train split: 0 examples [00:01, ? examples/s]Traceback (most recent call last):
  File "/home/snag0027/.local/lib/python3.10/site-packages/audiofile/core/convert.py", line 28, in convert
    run_sox(infile, outfile, offset, duration)
  File "/home/snag0027/.local/lib/python3.10/site-packages/audiofile/core/utils.py", line 131, in run_sox
    run(cmd)
  File "/home/snag0027/.local/lib/python3.10/site-packages/audiofile/core/utils.py", line 84, in run
    out = subprocess.check_output(
  File "/app/python/3.10.5/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/app/python/3.10.5/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/app/python/3.10.5/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/app/python/3.10.5/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sox'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/snag0027/.local/lib/python3.10/site-packages/audiofile/core/convert.py", line 32, in convert
    run_ffmpeg(infile, outfile, offset, duration)
  File "/home/snag0027/.local/lib/python3.10/site-packages/audiofile/core/utils.py", line 111, in run_ffmpeg
    run(cmd)
  File "/home/snag0027/.local/lib/python3.10/site-packages/audiofile/core/utils.py", line 84, in run
    out = subprocess.check_output(
  File "/app/python/3.10.5/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/app/python/3.10.5/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/app/python/3.10.5/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/app/python/3.10.5/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/snag0027/.local/lib/python3.10/site-packages/datasets/builder.py", line 1608, in _prepare_split_single
    for key, record in generator:
  File "/home/snag0027/.cache/huggingface/modules/datasets_modules/datasets/dataloadermultimodal/84c500e2c0e4323e8e54e8719d7409d1eaa628c9b4244aa8b08663953138d9a0/dataloadermultimodal.py", line 167, in _generate_examples
    audio_features = smile.process_file(os.path.join(audio_dir, folder, file))
  File "/home/snag0027/.local/lib/python3.10/site-packages/audinterface/core/feature.py", line 433, in process_file
    series = self.process.process_file(
  File "/home/snag0027/.local/lib/python3.10/site-packages/audinterface/core/process.py", line 327, in process_file
    y, files, starts, ends = self._process_file(
  File "/home/snag0027/.local/lib/python3.10/site-packages/audinterface/core/process.py", line 259, in _process_file
    signal, sampling_rate = utils.read_audio(
  File "/home/snag0027/.local/lib/python3.10/site-packages/audinterface/core/utils.py", line 150, in read_audio
    signal, sampling_rate = af.read(
  File "/home/snag0027/.local/lib/python3.10/site-packages/audiofile/core/io.py", line 397, in read
    convert(file, tmpfile, offset, duration)
  File "/home/snag0027/.local/lib/python3.10/site-packages/audiofile/core/convert.py", line 34, in convert
    raise binary_missing_error('ffmpeg')
FileNotFoundError: ffmpeg cannot be found.
Please make sure it is installed.
For further instructions visit: https://audeering.github.io/audiofile/installation.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/snag0027/speech-depression/cluster/train_ast_multistream.py", line 46, in <module>
    ds = load_dataset(
  File "/home/snag0027/.local/lib/python3.10/site-packages/datasets/load.py", line 1782, in load_dataset
    builder_instance.download_and_prepare(
  File "/home/snag0027/.local/lib/python3.10/site-packages/datasets/builder.py", line 872, in download_and_prepare
    self._download_and_prepare(
  File "/home/snag0027/.local/lib/python3.10/site-packages/datasets/builder.py", line 1649, in _download_and_prepare
    super()._download_and_prepare(
  File "/home/snag0027/.local/lib/python3.10/site-packages/datasets/builder.py", line 967, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/home/snag0027/.local/lib/python3.10/site-packages/datasets/builder.py", line 1488, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "/home/snag0027/.local/lib/python3.10/site-packages/datasets/builder.py", line 1644, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.builder.DatasetGenerationError: An error occurred while generating the dataset
                                                        